export const CITIES = [
  { id: 'beijing',      name: '北京',     lat: 39.90, lon: 116.41, province: '北京',   region: '华北' },
  { id: 'tianjin',      name: '天津',     lat: 39.13, lon: 117.20, province: '天津',   region: '华北' },
  { id: 'shijiazhuang', name: '石家庄',   lat: 38.04, lon: 114.51, province: '河北',   region: '华北' },
  { id: 'taiyuan',      name: '太原',     lat: 37.87, lon: 112.55, province: '山西',   region: '华北' },
  { id: 'hohhot',       name: '呼和浩特', lat: 40.81, lon: 111.65, province: '内蒙古', region: '华北' },

  { id: 'shanghai',     name: '上海',     lat: 31.23, lon: 121.47, province: '上海',   region: '华东' },
  { id: 'nanjing',      name: '南京',     lat: 32.06, lon: 118.80, province: '江苏',   region: '华东' },
  { id: 'suzhou',       name: '苏州',     lat: 31.30, lon: 120.62, province: '江苏',   region: '华东' },
  { id: 'wuxi',         name: '无锡',     lat: 31.57, lon: 120.30, province: '江苏',   region: '华东' },
  { id: 'yangzhou',     name: '扬州',     lat: 32.39, lon: 119.41, province: '江苏',   region: '华东' },
  { id: 'nantong',      name: '南通',     lat: 31.98, lon: 120.89, province: '江苏',   region: '华东' },
  { id: 'hangzhou',     name: '杭州',     lat: 30.25, lon: 120.15, province: '浙江',   region: '华东' },
  { id: 'ningbo',       name: '宁波',     lat: 29.87, lon: 121.55, province: '浙江',   region: '华东' },
  { id: 'wenzhou',      name: '温州',     lat: 28.02, lon: 120.67, province: '浙江',   region: '华东' },
  { id: 'fuzhou',       name: '福州',     lat: 26.07, lon: 119.30, province: '福建',   region: '华东' },
  { id: 'xiamen',       name: '厦门',     lat: 24.48, lon: 118.09, province: '福建',   region: '华东' },
  { id: 'hefei',        name: '合肥',     lat: 31.86, lon: 117.28, province: '安徽',   region: '华东' },
  { id: 'jinan',        name: '济南',     lat: 36.65, lon: 117.12, province: '山东',   region: '华东' },
  { id: 'qingdao',      name: '青岛',     lat: 36.07, lon: 120.37, province: '山东',   region: '华东' },
  { id: 'taian',        name: '泰安',     lat: 36.19, lon: 117.09, province: '山东',   region: '华东' },
  { id: 'linyi',        name: '临沂',     lat: 35.06, lon: 118.36, province: '山东',   region: '华东' },
  { id: 'yantai',       name: '烟台',     lat: 37.47, lon: 121.45, province: '山东',   region: '华东' },

  { id: 'chongqing',    name: '重庆',     lat: 29.56, lon: 106.55, province: '重庆',   region: '西南' },
  { id: 'chengdu',      name: '成都',     lat: 30.67, lon: 104.07, province: '四川',   region: '西南' },
  { id: 'guiyang',      name: '贵阳',     lat: 26.65, lon: 106.63, province: '贵州',   region: '西南' },
  { id: 'kunming',      name: '昆明',     lat: 25.05, lon: 102.73, province: '云南',   region: '西南' },
  { id: 'lhasa',        name: '拉萨',     lat: 29.65, lon: 91.13,  province: '西藏',   region: '西南' },

  { id: 'guangzhou',    name: '广州',     lat: 23.13, lon: 113.27, province: '广东',   region: '华南' },
  { id: 'shenzhen',     name: '深圳',     lat: 22.54, lon: 114.05, province: '广东',   region: '华南' },
  { id: 'nanning',      name: '南宁',     lat: 22.82, lon: 108.37, province: '广西',   region: '华南' },
  { id: 'haikou',       name: '海口',     lat: 20.02, lon: 110.32, province: '海南',   region: '华南' },
  { id: 'changsha',     name: '长沙',     lat: 28.23, lon: 112.94, province: '湖南',   region: '华中' },
  { id: 'wuhan',        name: '武汉',     lat: 30.59, lon: 114.30, province: '湖北',   region: '华中' },
  { id: 'nanchang',     name: '南昌',     lat: 28.68, lon: 115.88, province: '江西',   region: '华中' },

  { id: 'zhengzhou',    name: '郑州',     lat: 34.75, lon: 113.65, province: '河南',   region: '华中' },
  { id: 'xian',         name: '西安',     lat: 34.34, lon: 108.94, province: '陕西',   region: '西北' },
  { id: 'lanzhou',      name: '兰州',     lat: 36.06, lon: 103.79, province: '甘肃',   region: '西北' },
  { id: 'xining',       name: '西宁',     lat: 36.62, lon: 101.77, province: '青海',   region: '西北' },
  { id: 'yinchuan',     name: '银川',     lat: 38.49, lon: 106.23, province: '宁夏',   region: '西北' },
  { id: 'urumqi',       name: '乌鲁木齐', lat: 43.83, lon: 87.62,  province: '新疆',   region: '西北' },

  { id: 'shenyang',     name: '沈阳',     lat: 41.80, lon: 123.43, province: '辽宁',   region: '东北' },
  { id: 'dalian',       name: '大连',     lat: 38.90, lon: 121.60, province: '辽宁',   region: '东北' },
  { id: 'changchun',    name: '长春',     lat: 43.90, lon: 125.33, province: '吉林',   region: '东北' },
  { id: 'harbin',       name: '哈尔滨',   lat: 45.75, lon: 126.65, province: '黑龙江', region: '东北' },
];

export const CITY_LOOKUP = Object.fromEntries(CITIES.map((city) => [city.id, city]));
